[control-plane]
control-plane ansible_host=13.60.6.50 private_ip=10.0.1.46 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/capstone-key.pem

[workers]
worker-1 ansible_host=51.20.52.253 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/capstone-key.pem
worker-2 ansible_host=51.20.86.32 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/capstone-key.pem

[all:vars]
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
