apiVersion: v1
kind: Secret
metadata:
  name: taskapp-secret
  namespace: taskapp
type: Opaque
data:
  SECRET_KEY: YTNjNDE3MjBlNzkxMTQ4ZTE2ZDIzZjBlZDM4YjQyN2NjYzBlNjFmZWRkYmVlODczNzRkYWU0MGFiYmYyZjRiNg==
  DATABASE_PASSWORD: U3Ryb25nUGFzc3dvcmQyMDI0
